// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: x8ztdr6NwjtFcF6gdhDwfr
// Component: 5Zh2jaWV88
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_new_figma_test.module.css"; // plasmic-import: x8ztdr6NwjtFcF6gdhDwfr/projectcss
import * as sty from "./PlasmicMobileControlright.module.css"; // plasmic-import: 5Zh2jaWV88/css
import Vector4Icon from "./icons/PlasmicIcon__Vector4"; // plasmic-import: L7BY_8YYtd/icon

export const PlasmicMobileControlright__VariantProps = new Array();

export const PlasmicMobileControlright__ArgProps = new Array();

function PlasmicMobileControlright__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"mobileControl"}
        data-plasmic-override={overrides.mobileControl}
        className={classNames(defaultcss.all, sty.mobileControl)}
      >
        <div
          data-plasmic-name={"rectangle718"}
          data-plasmic-override={overrides.rectangle718}
          className={classNames(defaultcss.all, sty.rectangle718)}
        />

        <Vector4Icon
          data-plasmic-name={"svg"}
          data-plasmic-override={overrides.svg}
          className={classNames(defaultcss.all, sty.svg)}
          role={"img"}
        />
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "mobileControl", "rectangle718", "svg"],
  mobileControl: ["mobileControl", "rectangle718", "svg"],
  rectangle718: ["rectangle718"],
  svg: ["svg"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMobileControlright__ArgProps,
      internalVariantPropNames: PlasmicMobileControlright__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicMobileControlright__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMobileControlright";
  } else {
    func.displayName = `PlasmicMobileControlright.${nodeName}`;
  }
  return func;
}

export const PlasmicMobileControlright = Object.assign(
  // Top-level PlasmicMobileControlright renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    mobileControl: makeNodeComponent("mobileControl"),
    rectangle718: makeNodeComponent("rectangle718"),
    svg: makeNodeComponent("svg"),
    // Metadata about props expected for PlasmicMobileControlright
    internalVariantProps: PlasmicMobileControlright__VariantProps,
    internalArgProps: PlasmicMobileControlright__ArgProps
  }
);

export default PlasmicMobileControlright;
/* prettier-ignore-end */
